# Default initial positions for multi_robot's ros2_control fake system

initial_positions:
  J0_joint: 0
  J1_joint: 0
  J2_joint: 0.349
  J3_joint: -1.57
  J4_joint: 0
  J5_joint: 3.14
  J6_joint: 0
  chassis_x: 0
  chassis_y: 0
  j0: 0
  j1: -0.785
  j2: 0.523
  j3: 3.14
  j4: 0
  j5: 0
  j6: 0