# Default initial positions for multi_robot's ros2_control fake system

initial_positions:
  J0_joint: -0.715
  J1_joint: 0
  J2_joint: 0.349
  J3_joint: -1.047
  J4_joint: 0
  J5_joint: 3.14
  J6_joint: 0
  chassis_x: 0
  chassis_y: 0
  chassis_theta: 0
  j0: 0
  j1: 0
  j2: 0.715
  j3: 2.355
  j4: 0
  j5: 0
  j6: 0