# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - station_controller
    - whole_controller

  station_controller:
    type: FollowJointTrajectory
    joints:
      - j0
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    action_ns: follow_joint_trajectory
    default: true
  whole_controller:
    type: FollowJointTrajectory
    joints:
      - chassis_x
      - chassis_y
      - J0_joint
      - J1_joint
      - J2_joint
      - J3_joint
      - J4_joint
      - J5_joint
      - J6_joint
    action_ns: follow_joint_trajectory
    default: true