# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    station_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    whole_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

station_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
whole_controller:
  ros__parameters:
    joints:
      - chassis_x
      - chassis_y
      - chassis_theta
      - J0_joint
      - J1_joint
      - J2_joint
      - J3_joint
      - J4_joint
      - J5_joint
      - J6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true